name: orders-tests

on:
  pull_request:
    paths:
      - 'orders/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd orders && rm -rf node_modules package-lock.json && npm install && npm run test:ci
